web:
  image: wordpress:4.3-apache
  volumes:
    - "./www:/var/www/html"
  ports:
    - "8080:80"
  links:
    - db
  env_file:
    - env
db:
  image: mysql/mysql-server:5.6
#  volumes:
#    - "./mysql-data/var/lib/mysql:/var/lib/mysql"
  env_file:
    - env

#sftp:
#  image: atmoz/sftp
#  command: beta:beta:1002
#  volumes:
#    - "./www/media/img_source/:/home/beta/img_source"

